dist: precise
language: python
python:
- '2.6'
- '2.7'
- '3.5'
before_install:
- wget http://ubuntu.byte.nl/pool/hypernode/y/yara/yara_3.4.0+dfsg-2build1_amd64.deb
- wget http://ubuntu.byte.nl/pool/hypernode/y/yara/libyara3_3.4.0+dfsg-2build1_amd64.deb
- sudo dpkg -i *3.4.0*.deb
script:
- pip install yara-python requests-cache mock
- PYTHONPATH=mwscan nosetests -v mwscan/tests/test_mwscan.py
- python tools/validate_signatures.py
- bash tools/travis_test_magento_releases.sh
notifications:
  email: false
deploy:
  provider: s3
  region: eu-west-1
  access_key_id: AKIAJJX4SIC3YNRC5XIQ
  secret_access_key:
    secure: PevYvlUrScbBG1tqlyD14VkZuAVWjPcjNWVwME2mEbxFBDh/p/aH68iqnomaWhxvb+IpKFui+WQtLsraaUriB0V1g9X5UUURRgHSe7kl8e6a07VmFm0TOvuAARKKq6oUMrqm0KMprs2uwUb9Iv3s1I1IF3IQctRaHO9LKQmbZt+7EuEVGpNOh+fAE/B+NNV45htj5xAg8IXQW8XvMtcVCmayfI6da7DuvydkUor1TIJD0Bn+0UBHEyG5MsODeixXa5/qjzo0ZLrZgXlGMgGP9VckH3sCT1tNcHye799AFCtgJeWX/Vr4kcAZW/HPYRnvtyr/dxPiZMMpHnKVa+4D/+VhMGkFhcJO38uWOFs5VkaAuoJ7cOYf9iIHk9KICt6/v6WoPQhrqzRcjq/1FECrqS3qiCpt2z4jTVdH7pHu9ic6/UTQOPgmEtHsza40MF1Z1kYclz4NvgHg2BYaAuB6ZIJ8V0UglZNcT6TryCxOiorU8b9gInt5N8p5CHjUhA5y3jG5yoKMTYNuoaHM/Bzm1yPeehLLWnLhkQgN6Ej4KiaQpF4DCo18GK6bOPt9nQdQDr+XWPXTIXY/DRpYKms9Jh8jx6yduqYQLsbsqgVymouaNf38tavQdy7uGdIqAHW70CNiq0VeGdhu5ZeCkb2+Uj1teU9u7hccDQV9YckMSxs=
  bucket: mwscan
  local_dir: build
  acl: public_read
  skip_cleanup: true
  on:
    repo: gwillem/magento-malware-scanner
