language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"

before_install:
  # hack: use yara pkgs from xenial (trusty has yara 2.x)
  - echo "deb http://fi.archive.ubuntu.com/ubuntu/ xenial main restricted" | sudo tee /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install yara -y

script:
  - pip install yara-python requests-cache mock
  - PYTHONPATH=mwscan nosetests -v mwscan/tests/test_mwscan.py
  - python tools/validate_signatures.py

  # This will only run under Py3 and when the rules have changed
  - bash tools/travis_test_magento_releases.sh

notifications:
  email: false